name: car_dashboard
description: "Car dashboard"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  #  Themes
  cupertino_icons: ^1.0.8
  theme_tailor: ^3.0.1
  theme_tailor_annotation: ^3.0.1
  intl: ^0.19.0

  # State manager
  provider: ^6.1.2
  flutter_keyboard_visibility: ^6.0.0

  # Storage
  shared_preferences: ^2.3.2

  #Navigation
  go_router: ^14.6.2

  #Widgets
  draggable_expandable_fab: ^1.0.0
  gap: ^3.0.1
  flextras: ^1.0.0
  awesome_circular_chart: ^1.1.0
  syncfusion_flutter_charts: ^27.1.52
  flutter_toggle_button: ^0.0.3
  dotted_border: ^2.1.0

  #Media
  flutter_svg: ^2.0.10+1
  flutter_3d_controller: ^2.0.2
  o3d: ^3.1.2
  image_picker: ^1.1.2
  file_picker: ^5.2.3
#  record: ^5.0.0
  path_provider: ^2.1.5
  audioplayers: ^5.2.0
  audio_waveforms: ^1.0.4
  permission_handler: ^11.0.1
  just_audio: ^0.9.7 # For audio playback
#  audio_waveforms: ^0.4.0 # For visualizing waveforms
  just_waveform: ^0.0.5

  #Other
  desktop_window: ^0.4.1
  menu_bar: ^0.5.3
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  calendar_view: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  go_router_builder: ^2.7.1
  flutter_gen_runner: ^5.8.0
  json_serializable: ^6.8.0

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans/DMSans-ExtraBold.ttf
          weight: 800
